export const ALLOYED_METALS_LIST_QUERY_KEY = "ALLOYED_METALS_LIST_QUERY_KEY";
export const ALLOYED_METAL_QUERY_KEY = "ALLOYED_METAL_QUERY_KEY";
export const ALLOYED_METAL_PURCHASES_QUERY_KEY = "ALLOYED_METAL_PURCHASES_QUERY_KEY";
export const ALLOYED_METALS_TOTAL_QUERY_KEY = "ALLOYED_METALS_TOTAL_QUERY_KEY";
