export enum TabKeys {
  DETAILS = "DETAILS",
  CAD = "CAD",
  TECHNICAL_SHEET = "TECHNICAL_SHEET",
  LABOUR = "LABOUR",
  DIAMONDS = "DIAMONDS",
  GEMSTONES = "GEMSTONES",
  METALS = "METALS",
  SUMMARY = "SUMMARY",
}
