export enum TabKeys {
  DETAILS = "DETAILS",
  CAD = "CAD",
  TECHNICAL_SHEET = "TECHNICAL_SHEET",
  LABOUR = "LABOUR",
  DIAMONDS = "DIAMONDS",
  GEMSTONES = "GEMSTONES",
  AVAILABLE = "AVAILABLE",
  SOLD = "SOLD",
  MEMO_OUT = "MEMO_OUT",
  METALS = "METALS",
  SUMMARY = "SUMMARY",
}
