export const OTHER_MATERIALS_QUERY_KEY = "OTHER_MATERIALS_QUERY_KEY";
export const OTHER_MATERIAL_QUERY_KEY = "OTHER_MATERIAL_QUERY_KEY";
export const OTHER_MATERIAL_TRANSACTIONS_QUERY_KEY = "OTHER_MATERIAL_TRANSACTIONS_QUERY_KEY";
