export const DIAMOND_RECORDS_LIST_QUERY_KEY = "DIAMOND_RECORDS_LIST_QUERY_KEY";
export const DIAMONDS_TOTAL_VALUE_QUERY_KEY = "DIAMONDS_TOTAL_VALUE_QUERY_KEY";
export const DIAMOND_SHAPES_QUERY_KEY = "DIAMOND_SHAPES_QUERY_KEY";
export const DIAMOND_USAGE_QUERY_KEY = "DIAMOND_USAGE_QUERY_KEY";
export const DIAMOND_USAGE_STATISTICS_QUERY_KEY = "DIAMOND_USAGE_STATISTICS_QUERY_KEY";
