export const STOCK_ITEMS_LIST_QUERY_KEY = "STOCK_ITEMS_LIST_QUERY_KEY";
export const STOCK_STATISTIC_QUERY_KEY = "STOCK_STATISTIC_QUERY_KEY";
export const STOCK_ITEM_QUERY_KEY = "STOCK_ITEM_QUERY_KEY";
