export enum ApiErrorCodes {
  CANNOT_DELETE = "CANNOT_DELETE",
  CANNOT_MOVE_ORDER_TO_STOCK_TASKS_NOT_COMPLETED = "CANNOT_MOVE_ORDER_TO_STOCK_TASKS_NOT_COMPLETED",
  CHANGE_ASSIGNED_STATUS_ERROR = "CHANGE_ASSIGNED_STATUS_ERROR",
  CHANGE_MEMO_OUT_STATUS_ORDER_ERROR = "CHANGE_MEMO_OUT_STATUS_ORDER_ERROR",
  CHANGE_MEMO_OUT_STATUS_NO_ORDER_ERROR = "CHANGE_MEMO_OUT_STATUS_NO_ORDER_ERROR",
  CHANGE_AVAILABLE_STATUS_NO_ORDER_ERROR = "CHANGE_AVAILABLE_STATUS_NO_ORDER_ERROR",
  CHANGE_AVAILABLE_STATUS_ORDER_ERROR = "CHANGE_AVAILABLE_STATUS_ORDER_ERROR",
  CHANGE_SOLD_RETURNED_STATUS_ERROR = "CHANGE_SOLD_RETURNED_STATUS_ERROR",
  CANNOT_DELETE_ORDER_WITH_LABOUR_ERROR = "CANNOT_DELETE_ORDER_WITH_LABOUR_ERROR",
  CHANGE_ASSIGNED_GEMSTONE_STATUS_ERROR = "CHANGE_ASSIGNED_GEMSTONE_STATUS_ERROR",
  INVALID_DATA = "INVALID_DATA",
}
