export const GEMSTONE_LIST_QUERY_KEY = "GEMSTONE_LIST_QUERY_KEY";
export const GEMSTONES_SEARCH_QUERY_KEY = "GEMSTONES_SEARCH_QUERY_KEY";
export const GEMSTONE_QUERY_KEY = "GEMSTONE_QUERY_KEY";
export const GEMSTONE_PAYMENT_STATUSES_QUERY_KEY = "GEMSTONE_PAYMENT_STATUSES_QUERY_KEY";
export const GEMSTONE_USAGE_STATISTICS_QUERY_KEY = "GEMSTONE_USAGE_STATISTICS_QUERY_KEY";
