export const ALLOY_QUERY_KEY = "ALLOY_QUERY_KEY";
export const ALLOYS_LIST_QUERY_KEY = "ALLOYS_LIST_QUERY_KEY";
export const ALLOYS_PURCHASES_LIST_QUERY_KEY = "ALLOYS_PURCHASES_LIST_QUERY_KEY";
export const ALLOY_PURCHASE_QUERY_KEY = "ALLOY_PURCHASE_QUERY_KEY";
