export enum OrderStatus {
  AssayCompleted = "ASSAY_COMPLETED",
  AtTheCasting = "AT_THE_CASTING",
  Finished = "FINISHED",
  InCad = "IN_CAD",
  InMounting = "IN_MOUNTING",
  InMountingBox = "IN_MOUNTING_BOX",
  InPolishing = "IN_POLISHING",
  InSetting = "IN_SETTING",
  InSettingBox = "IN_SETTING_BOX",
  Invoiced = "INVOICED",
  MasterPieceBox = "MASTER_PIECE_BOX",
  MountingCompleted = "MOUNTING_COMPLETED",
  OutForAssay = "OUT_FOR_ASSAY",
  Polished = "POLISHED",
  PreppedForSetting = "PREPPED_FOR_SETTING",
  Prototyping = "PROTOTYPING",
  QcMounting = "QC_MOUNTING",
  QcPassed = "QC_PASSED",
  QualityControl = "QUALITY_CONTROL",
  ReadyForAssay = "READY_FOR_ASSAY",
  ReadyForInvoice = "READY_FOR_INVOICE",
  ReadyToCasting = "READY_TO_CASTING",
  ReceivedFromCasting = "RECEIVED_FROM_CASTING",
  Recycled = "RECYCLED",
  Rejected = "REJECTED",
  SandBlasting = "SAND_BLASTING",
  SentToEnamel = "SENT_TO_ENAMEL",
  SettingCompleted = "SETTING_COMPLETED",
}

export const orderStatusNameMap: Record<OrderStatus, string> = {
  [OrderStatus.AssayCompleted]: "Assay Completed",
  [OrderStatus.AtTheCasting]: "At the pre-casting",
  [OrderStatus.Finished]: "Finished",
  [OrderStatus.InCad]: "In CAD",
  [OrderStatus.InMounting]: "In Mounting",
  [OrderStatus.InMountingBox]: "In Mounting Box",
  [OrderStatus.InPolishing]: "In Polishing",
  [OrderStatus.InSetting]: "In Setting",
  [OrderStatus.InSettingBox]: "In Setting Box",
  [OrderStatus.Invoiced]: "Invoiced",
  [OrderStatus.MasterPieceBox]: "Master Piece Box",
  [OrderStatus.MountingCompleted]: "Mounting Competed",
  [OrderStatus.OutForAssay]: "Out for Assay",
  [OrderStatus.Polished]: "Polished",
  [OrderStatus.PreppedForSetting]: "Prepped for Setting",
  [OrderStatus.Prototyping]: "Prototyping",
  [OrderStatus.QcMounting]: "QC Mounting",
  [OrderStatus.QcPassed]: "QC Passed",
  [OrderStatus.QualityControl]: "Quality Control",
  [OrderStatus.ReadyForAssay]: "Ready for Assay",
  [OrderStatus.ReadyForInvoice]: "Ready for Invoice",
  [OrderStatus.ReadyToCasting]: "Ready to Casting",
  [OrderStatus.ReceivedFromCasting]: "Received from Casting",
  [OrderStatus.Recycled]: "Recycled",
  [OrderStatus.Rejected]: "Rejected",
  [OrderStatus.SandBlasting]: "Sand Blasting",
  [OrderStatus.SentToEnamel]: "Sent to Enamel",
  [OrderStatus.SettingCompleted]: "Setting Completed",
};
