export const PURE_METAL_SUMMARY_QUERY_KEY = "PURE_METAL_SUMMARY_QUERY_KEY";
export const PURE_METALS_SUMMARY_QUERY_KEY = "PURE_METALS_SUMMARY_QUERY_KEY";
export const PURE_METALS_LIST_QUERY_KEY = "PURE_METALS_LIST_QUERY_KEY";
export const PURE_METALS_PURCHASES_LIST_QUERY_KEY = "PURE_METALS_PURCHASES_LIST_QUERY_KEY";
export const METALS_QUERY_KEY = "METALS_QUERY_KEY";
export const PURCHASE_SUMMARY_QUERY_KEY = "PURCHASE_SUMMARY_QUERY_KEY";
export const ALLOY_PARAMETERS_QUERY_KEY = "ALLOY_PARAMETERS_QUERY_KEY";
